version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
  open-pull-requests-limit: 10
  reviewers:
  - chubchenko
  ignore:
  - dependency-name: rack-test
    versions:
    - "> 0"
