require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  ExcludedMethods:
    - describe

RSpec/DescribeClass:
  Exclude:
    - 'spec/integration/**/*'

Naming/FileName:
  Exclude:
    - 'lib/mailgun-tracking.rb'
