require:
  - "rubocop-performance"
  - "rubocop-rspec"

AllCops:
  Exclude:
    - "bin/*"
  TargetRubyVersion: 2.4
  NewCops: enable

Layout/LineLength:
  Max: 120

Style/AccessorGrouping:
  EnforcedStyle: separated

Style/OptionalBooleanParameter:
  Exclude:
    - "lib/mailgun/tracking.rb"

Metrics/BlockLength:
  ExcludedMethods:
    - describe

RSpec/DescribeClass:
  Exclude:
    - "spec/integration/**/*"

Naming/FileName:
  Exclude:
    - "lib/mailgun-tracking.rb"
