require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'gemfiles/**/*'

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  ExcludedMethods:
    - describe

Naming/MethodName:
  IgnoredPatterns:
    - '\APOST'

RSpec/DescribeClass:
  Exclude:
    - 'spec/integration/**/*'
