require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  ExcludedMethods:
    - describe

Naming/MethodName:
  IgnoredPatterns:
    - '\APOST'

RSpec/DescribeClass:
  Exclude:
    - 'spec/integration/**/*'
