sudo: false
dist: trusty

cache:
  bundler: true

language: ruby

rvm:
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - ruby-head

gemfile:
  - gemfiles/rack.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_head.gemfile
  - gemfiles/sinatra.gemfile

matrix:
  exclude:
    - rvm: 2.2.9
      gemfile: gemfiles/rails_head.gemfile
    - rvm: 2.3.6
      gemfile: gemfiles/rails_head.gemfile
  allow_failures:
    - rvm: ruby-head
    - gemfile: gemfiles/rails_head.gemfile
  fast_finish: true

before_install:
  - gem install bundler

install:
  - bundle install
  - bundle exec appraisal install

script:
  - bundle exec appraisal rack rake spec:integration:rack
  - bundle exec appraisal rails-4.2 rake spec:integration:rails
  - bundle exec appraisal rails-5.0 rake spec:integration:rails
  - bundle exec appraisal rails-5.1 rake spec:integration:rails
  - bundle exec appraisal rails-5.2 rake spec:integration:rails
  - bundle exec appraisal rails-head rake spec:integration:rails
  - bundle exec appraisal sinatra rake spec:integration:sinatra
  - bundle exec rake spec:unit

after_success:
  - bundle exec codeclimate-test-reporter
