sudo: false
dist: trusty

cache:
  bundler: true

language: ruby

rvm:
  - 2.1.10
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - ruby-head

gemfile:
  - gemfiles/sinatra.gemfile
  - gemfiles/rack.gemfile
  - gemfiles/rails_4.2.gemfile

after_success:
  - bundle exec codeclimate-test-reporter
