sudo: false
dist: trusty

cache:
  bundler: true

language: ruby

rvm:
  - 2.1.10
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

before_install:
  - gem update --system
  - gem update --remote bundler

after_success:
  - bundle exec codeclimate-test-reporter
