version: 1.0.{build}-{branch}

environment:
  matrix:
    - RUBY_VERSION: 24
    - RUBY_VERSION: 25
    - RUBY_VERSION: 26

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - bundle install

build: off

test_script:
  - bundle exec rake spec:unit
