name: Default

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby: ['2.4.x', '2.5.x', '2.6.x']
        gemfile: [
          'gemfiles/rails_4_2.gemfile',
          'gemfiles/rails_5_0.gemfile',
          'gemfiles/rails_5_1.gemfile',
          'gemfiles/rails_5_2.gemfile',
          'gemfiles/rails_6_0.gemfile',
          'gemfiles/rails_head.gemfile'
        ]
        exclude:
          - ruby: '2.4.x'
            gemfile: 'gemfiles/rails_6_0.gemfile'
          - ruby: '2.4.x'
            gemfile: 'gemfiles/rails_head.gemfile'

    steps:
      - uses: actions/checkout@master

      - name: Setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}



      # - uses: actions/checkout@v1
      #
      # - name: ...
      #   uses: actions/setup-ruby@v1
      #   with:
      #     ruby-version: ${{matrix.ruby}}
      #
      # - name: ...
      #   run: |
      #     gem install bundler
      #     bundle install && bundle exec appraisal install
      #     bundle exec rake
      #
      #     bundle exec appraisal rails-4-2 rake spec:integration:rails
      #     bundle exec appraisal rails-5-0 rake spec:integration:rails
      #     bundle exec appraisal rails-5-1 rake spec:integration:rails
      #     bundle exec appraisal rails-5-2 rake spec:integration:rails
      #     bundle exec appraisal rails-6-0 rake spec:integration:rails
      #     bundle exec appraisal rails-head rake spec:integration:rails
      #
      #     bundle exec appraisal sinatra rake spec:integration:sinatra
      #
      #     bundle exec appraisal rack rake spec:integration:rack
      #
      #     bundle exec appraisal hanami-1 rake spec:integration:hanami
      #     bundle exec appraisal hanami-head rake spec:integration:hanami
