name: docs

on:
  push:
    branches:
    - master
    paths:
    - "**/*.md"
  pull_request:
    paths:
    - "**/*.md"

jobs:
  mdl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x
      - name: Lint Markdown files with MDL
        run: |
          gem install mdl
          mdl .
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x
      - name: Lint Markdown files with RuboCop
        run: |
          gem install bundler
          bundle install --gemfile gemfiles/rubocop.gemfile --jobs 4 --retry 3
          bundle exec --gemfile gemfiles/rubocop.gemfile rubocop -c .rubocop-md.yml --parallel

  forspell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x
      - name: Lint Markdown files with Forspell
        run: |
          sudo apt-get install hunspell
          gem install forspell
          forspell .
