name: build

on:
  push:
    branches:
    - master
  pull_request:

  schedule:
    - cron: '0 0 * * *'

jobs:
  rspec:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.4, 2.5, 2.6, 2.7, jruby]
        gemfile: [
          'gemfiles/rails_5_0.gemfile',
          'gemfiles/rails_5_1.gemfile',
          'gemfiles/rails_5_1.gemfile',
          'gemfiles/rails_6_0.gemfile',
          'gemfiles/rails_head.gemfile',
          'gemfiles/hanami_1.gemfile',
          'gemfiles/hanami_head.gemfile',
          'gemfiles/sinatra.gemfile'
        ]
        exclude:
          - ruby: 2.4
            gemfile: 'gemfiles/rails_6_0.gemfile'
          - ruby: 2.4
            gemfile: 'gemfiles/rails_head.gemfile'
    steps:
      - uses: actions/checkout@master
      - name: Set up Ruby
        uses: eregon/use-ruby-action@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Setting up Bundler
        run: |
          gem install bundler
          bundle config --global gemfile ${{ matrix.gemfile }}
          bundle install --jobs 4 --retry 3
      - name: Run RSpec
        run: |
          bundle exec rspec
