name: JRuby Build

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  rspec-jruby:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: jruby
      - name: Setting up Bundler
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Run RSpec
        run: |
          bundle exec rspec
