name: RuboCop

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby 2.7
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7.x
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/rubocop.gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-
    - name: Setting up Bundler
      run: |
        gem install bundler
        bundle config path vendor/bundle
        bundle install --gemfile gemfiles/rubocop.gemfile --jobs 4 --retry 3
    - name: Run RuboCop
      run: |
        bundle exec --gemfile gemfiles/rubocop.gemfile rubocop --parallel
