name: RuboCop

on:
  push:
  pull_request:

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Ruby 2.4
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.4.x
      - name: Install a bundler gem
        run: |
          gem install bundler
      - name: Install the current environment to the system
        run:
          bundle install --gemfile gemfiles/rubocop.gemfile --jobs 4 --retry 3
      - name: Lint source code with RuboCop
        run: |
          bundle exec --gemfile gemfiles/rubocop.gemfile rubocop
